server:
  port: ${PORT:40600}
spring:
  application:
    name: xc-service-learning
  datasource:
        url: jdbc:mysql://localhost:3306/xc_learning?serverTimezone=Asia/Shanghai&characterEncoding=utf8
        username: root
        password: cxg200888
        hikari:
          maximum-pool-size: 30
          minimum-idle: 10
#rabbitmq配置
  rabbitmq:
        host: 192.168.25.128
        username: 2850105498
        password: cxg200888
        virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:50101/eureka
    registry-fetch-interval-seconds: 5
  instance:
     lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
     lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
     prefer-ip-address: true
     ip-address: 127.0.0.1
     instance-id: ${spring.application.name}:${server.port}
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间